apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels: # these are replicaset lables
    app: mysql
    tier: db
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
  # these are used to select the pod to create replicas
    matchLabels:
      app: mysql
      tier: db
      project: expense
  # this is pod definition
  template:
    metadata:
    # these lables belongs to pod
      labels:
        tier: db
        app: mysql
        project: expense
    spec:
      containers:
      - name: mysql
        image: prameela0/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    tier: db
    app: mysql
    project: expense
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306   